language: java

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

before_install:
  - export MAVEN_OPTS=-Xmx1024m

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - ./build/travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "jooby"
    token: $SONAR_TOKEN
